package faceit_cc

import (
	"testing"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
)

func TestValidateUuid(t *testing.T) {
	assert := assert.New(t)

	tests := []struct {
		Description    string
		Input          string
		ExpectedResult bool
	}{
		{
			Description:    "when the input is not a valid uuid",
			Input:          "foo",
			ExpectedResult: false,
		},
		{
			Description:    "when the input is a valid uuid",
			Input:          "d2a7924e-765f-4949-bc4c-219c956d0f8b",
			ExpectedResult: true,
		},
		{
			Description:    "when the input is an uuid without -",
			Input:          "d2a7924e765f4949bc4c-219c956d0f8b",
			ExpectedResult: false,
		},
		{
			Description:    "when the input is a valid uuid generated by uuid package",
			Input:          uuid.New().String(),
			ExpectedResult: true,
		},
	}

	for _, test := range tests {
		t.Run(test.Description, func(t *testing.T) {
			output := ValidateUuid(test.Input)
			assert.Equal(test.ExpectedResult, output)
		})
	}
}
