version: '2.4'
services:

  faceit:
    container_name: faceit
    image: faceit:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file: docker/env
    ports:
      - 9001:9001
    links:
      - mysql_faceit
      - zookeeper
    depends_on:
      - mysql_faceit
      - zookeeper
    networks:
      - faceit_cc

  mysql_faceit:
    container_name: mysql_faceit
    build:
      context: docker/mysql/
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysqluser
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw 
    networks:
      - faceit_cc
    healthcheck:
      test: "mysql faceit_cc -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 20s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - faceit_cc      

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - faceit_cc      

networks:
  faceit_cc:
    driver: bridge